import { AssetButton, ImageAssetButton, TextAssetbutton } from './Pickers/assetPicker';
import { TextInputinput, ParagraphInputinput } from './Inputs/text';
import { NumberInputinput, VectorInputinput } from './Inputs/number';
import { RadioInput, RadioIconInput } from './Inputs/radio';
import { SelectInput } from './Inputs/select';
import { Checkbox } from './Inputs/checkbox';
import { SliderInput } from './Inputs/slider';
import { InputGroupSwitch } from './Layers/layer';
import './styles/main.sass';
import './styles/font.css';
import './styles/inputs.sass';
import './styles/suggestions.sass';
import './styles/modal.sass';
import './styles/uislider.sass';
import './styles/checkbox.sass';
import './styles/radio.sass';
export declare class TestDesign extends InputGroupSwitch {
    backgroundBottom: HTMLElement;
    backgroundTop: HTMLElement;
    colorPalette: HTMLElement;
    constructor();
    color: AssetButton;
    asset: AssetButton;
    asset2: ImageAssetButton;
    asset3: TextAssetbutton;
    number: NumberInputinput;
    numberunit: NumberInputinput;
    slider: SliderInput;
    sliderloga: SliderInput;
    vector: VectorInputinput;
    radio: RadioInput;
    radioicon: RadioIconInput;
    select: SelectInput;
    checkbox: Checkbox;
    text: TextInputinput;
    paragraph: ParagraphInputinput;
    addInputs(): void;
}
